# Copyright (c) 2026-present Romain Leroux. All rights reserved.

#' @title Optimization Class
#' @name Optimization
#' @description
#' The `Optimization` class is the base class for managing design optimization
#' processes in PFIM. It allows comparison of the performance of the initial
#' design against the optimal design generated by the optimization algorithm.
#' @slot optimisationDesign \code{list}. Stores the evaluations (FIM, criteria, SE)
#' of both the initial and the optimal design.
#' @slot optimisationAlgorithmOutputs \code{list}. Contains the logs and
#' algorithm-specific outputs produced during the optimization process.
#' @slot optimizer \code{character}. Name of the optimization algorithm to use.
#' Must be one of \code{"FedorovWynnAlgorithm"}, \code{"MultiplicativeAlgorithm"},
#' \code{"SimplexAlgorithm"}, \code{"PSOAlgorithm"}, or \code{"PGBOAlgorithm"}.
#' When provided, the constructor acts as a factory and returns an instance of
#' the corresponding sub-class directly.
#' @slot optimizerParameters \code{list}. Named list of algorithm-specific
#' hyperparameters passed to the sub-class constructor when \code{optimizer} is set.
#' @param optimisationDesign A list storing the evaluations (FIM, criteria, SE)
#' of both the initial and the optimal design.
#' @param optimisationAlgorithmOutputs A list containing the logs and
#' algorithm-specific outputs produced during the optimization process.
#' @param optimizer A character string naming the optimization algorithm.
#' @param optimizerParameters A named list of algorithm-specific hyperparameters.
#' @inheritParams PFIMProject
#' @return An object of class \code{Optimization}, or of the corresponding
#' algorithm sub-class when \code{optimizer} is supplied.
#' @include PFIMProject.R
#' @examples
#' \dontrun{
#'
#' Examples from Vignette 1 and 2
#'
#' # 1. Multiplicative algorithm for population FIM optimization
#' optimizationMultPopFIM = Optimization(
#'   name                = "PKPD_ODE_multi_doses_populationFIM",
#'   modelEquations      = modelEquations,
#'   modelParameters     = modelParameters,
#'   modelError          = modelError,
#'   optimizer           = "MultiplicativeAlgorithm",
#'   optimizerParameters = list(
#'     lambda             = 0.99,    # near-unity: slow but stable weight updates
#'     numberOfIterations = 1000,    # maximum multiplicative iterations
#'     weightThreshold    = 0.01,    # discard protocols with weight < 1%
#'     delta              = 1e-04,   # stop when D-criterion improvement < 0.01%
#'     showProcess        = TRUE
#'   ),
#'   designs             = list(designConstraint),
#'   fimType             = "population",
#'   outputs             = list("RespPK" = "Cc", "RespPD" = "E"),
#'   odeSolverParameters = list(atol = 1e-8, rtol = 1e-8)
#' )
#'
#' # 2. Fedorov-Wynn algorithm for population FIM optimization
#' optimizationFWPopFIM = Optimization(
#'   name                = "PKPD_ODE_multi_doses_populationFIM",
#'   modelEquations      = modelEquations,
#'   modelParameters     = modelParameters,
#'   modelError          = modelError,
#'   optimizer           = "FedorovWynnAlgorithm",
#'   optimizerParameters = list(
#'     elementaryProtocols   = initialElementaryProtocols,
#'     numberOfSubjects      = numberOfSubjects,
#'     proportionsOfSubjects = proportionsOfSubjects,
#'     showProcess           = TRUE
#'   ),
#'   designs             = list(designConstraint),
#'   fimType             = "population",
#'   outputs             = list("RespPK" = "Cc", "RespPD" = "E"),
#'   odeSolverParameters = list(atol = 1e-8, rtol = 1e-8)
#' )
#'
#' # 3. Particle Swarm Optimization (PSO) algorithm
#' optimizationPSOPopFIM = Optimization(
#'   name                = "optimizationExamplePSO",
#'   modelFromLibrary    = modelFromLibrary,
#'   modelParameters     = modelParameters,
#'   modelError          = modelError,
#'   optimizer           = "PSOAlgorithm",
#'   optimizerParameters = list(
#'     maxIteration                = 100,   # number of swarm update cycles
#'     populationSize              = 50,    # number of particles
#'     personalLearningCoefficient = 2.05,  # c1: attraction toward personal best
#'     globalLearningCoefficient   = 2.05,  # c2: attraction toward global best
#'     seed                        = 42,    # reproducibility
#'     showProcess                 = FALSE  # suppress iteration-level output
#'   ),
#'   designs             = list(design2),
#'   fimType             = "population",
#'   outputs             = list("RespPK")
#' )
#'
#' # 4. Population-Based Gradient Optimization (PGBO) algorithm
#' optimizationPGBOPopFIM = Optimization(
#'   name                = "optimizationExamplePGBO",
#'   modelFromLibrary    = modelFromLibrary,
#'   modelParameters     = modelParameters,
#'   modelError          = modelError,
#'   optimizer           = "PGBOAlgorithm",
#'   optimizerParameters = list(
#'     N              = 30,    # population of 30 candidate designs
#'     muteEffect     = 0.65,  # mutation amplitude (65% of window width)
#'     maxIteration   = 1000,  # total evolutionary steps
#'     purgeIteration = 200,  # reinitialize worst solutions every 200 steps
#'     seed           = 42,
#'     showProcess    = FALSE
#'   ),
#'   designs             = list(design2),
#'   fimType             = "population",
#'   outputs             = list("RespPK")
#' )
#'
#' # 5. Nelder-Mead Simplex algorithm
#' optimizationSimplexPopFIM = Optimization(
#'   name                = "optimizationExampleSimplex",
#'   modelFromLibrary    = modelFromLibrary,
#'   modelParameters     = modelParameters,
#'   modelError          = modelError,
#'   optimizer           = "SimplexAlgorithm",
#'   optimizerParameters = list(
#'     pctInitialSimplexBuilding = 10,    # initial spread: 10% of window widths
#'     maxIteration              = 1000,  # max Nelder-Mead iterations
#'     tolerance                 = 1e-10, # convergence on relative D-criterion change
#'     showProcess               = FALSE
#'   ),
#'   designs             = list(design2),
#'   fimType             = "population",
#'   outputs             = list("RespPK")
#' )
#'
#' }
#' @template copyright
#' @export

Optimization = new_class(
  "Optimization",
  package = "PFIM",
  parent  = PFIMProject,
  properties = list(
    optimisationDesign           = new_property(class_list,      default = list()),
    optimisationAlgorithmOutputs = new_property(class_list,      default = list()),
    name                         = new_property(class_character, default = character(0)),
    modelParameters              = new_property(class_list,      default = list()),
    modelEquations               = new_property(class_list,      default = list()),
    modelFromLibrary             = new_property(class_list,      default = list()),
    modelError                   = new_property(class_list,      default = list()),
    designs                      = new_property(class_list,      default = list()),
    outputs                      = new_property(class_list,      default = list()),
    fimType                      = new_property(class_character, default = character(0)),
    odeSolverParameters          = new_property(class_list,      default = list()),
    # ── Factory slots ──────────────────────────────────────────────────────────
    optimizer                    = new_property(class_character, default = character(0)),
    optimizerParameters          = new_property(class_list,      default = list())
  ),
  validator = function(self) {
    # Sub-class instances created with no arguments (e.g. FedorovWynnAlgorithm(),
    # MultiplicativeAlgorithm(), ...) serve as empty dispatch tokens inside
    # defineOptimizationAlgorithm(). They have all list slots at their default
    # empty values, so skip structural validation for them.
    isDispatchToken = length(prop(self, "outputs"))         == 0L &&
      length(prop(self, "designs"))         == 0L &&
      length(prop(self, "modelParameters")) == 0L
    if (isDispatchToken) return(NULL)

    errors = character(0)
    if (length(prop(self, "name")) > 0L && (!nzchar(trimws(prop(self, "name")))))
      errors = c(errors, "@name must be a non-empty string.")
    validFimTypes = c("population", "individual", "Bayesian")
    if (length(prop(self, "fimType")) > 0L && !(prop(self, "fimType") %in% validFimTypes))
      errors = c(errors, sprintf(
        "@fimType must be one of: %s. Got: '%s'.",
        paste(validFimTypes, collapse = ", "), prop(self, "fimType")
      ))
    if (length(prop(self, "designs")) == 0L)
      errors = c(errors, "@designs must contain at least one design.")
    hasEquations = length(prop(self, "modelEquations"))  > 0L
    hasFromLib   = length(prop(self, "modelFromLibrary")) > 0L
    if (!hasEquations && !hasFromLib)
      errors = c(errors, "Either @modelEquations or @modelFromLibrary must be provided.")
    if (length(prop(self, "modelParameters")) == 0L)
      errors = c(errors, "@modelParameters must contain at least one parameter.")
    if (length(prop(self, "modelError")) == 0L)
      errors = c(errors, "@modelError must contain at least one error model.")
    if (length(prop(self, "outputs")) == 0L)
      errors = c(errors, "@outputs must contain at least one output.")
    if (length(errors) == 0L) NULL else errors
  },
  constructor = function(
    optimisationDesign           = list(),
    optimisationAlgorithmOutputs = list(),
    name                         = character(0),
    modelParameters              = list(),
    modelEquations               = list(),
    modelFromLibrary             = list(),
    modelError                   = list(),
    designs                      = list(),
    outputs                      = list(),
    fimType                      = character(0),
    odeSolverParameters          = list(),
    optimizer                    = character(0),
    optimizerParameters          = list()
  ) {
    new_object(
      .parent                      = PFIMProject(name = name),
      optimisationDesign           = optimisationDesign,
      optimisationAlgorithmOutputs = optimisationAlgorithmOutputs,
      name                         = name,
      modelParameters              = modelParameters,
      modelEquations               = modelEquations,
      modelFromLibrary             = modelFromLibrary,
      modelError                   = modelError,
      designs                      = designs,
      outputs                      = outputs,
      fimType                      = fimType,
      odeSolverParameters          = odeSolverParameters,
      optimizer                    = optimizer,
      optimizerParameters          = optimizerParameters
    )
  }
)

# ==============================================================================
# FACTORY WRAPPER
# ==============================================================================
#   - Keep the Optimization constructor simple (just stores properties).
#   - Move the factory logic into a plain R wrapper function that SHADOWS the
#     S7 constructor name.  Plain functions are not subject to S7's constructor
#     machinery, so the dispatch is transparent.
#   - Save the original S7 class constructor as .Optimization_S7 so that
#     (a) the factory wrapper can delegate to it, and
#     (b) sub-class constructors in e.g. FedorovWynnAlgorithm.R can call it
#         with the full set of parent-class arguments to build a valid parent
#         instance before new_object() creates the sub-class object.
# ==============================================================================

.Optimization_S7 = Optimization   # preserve the real S7 class/constructor

#' @rdname Optimization
#' @export
Optimization = function(
    optimisationDesign           = list(),
    optimisationAlgorithmOutputs = list(),
    name                         = character(0),
    modelParameters              = list(),
    modelEquations               = list(),
    modelFromLibrary             = list(),
    modelError                   = list(),
    designs                      = list(),
    outputs                      = list(),
    fimType                      = character(0),
    odeSolverParameters          = list(),
    optimizer                    = character(0),
    optimizerParameters          = list()
) {
  # All optimizeDesign() methods read algo-specific params from
  # prop(optimizationObject, "optimizerParameters"). Sub-classes are only
  # used as empty dispatch tokens inside defineOptimizationAlgorithm().
  # → Always return a plain Optimization object; never dispatch to subclasses.
  validOptimizers = c(
    "FedorovWynnAlgorithm", "MultiplicativeAlgorithm",
    "SimplexAlgorithm", "PSOAlgorithm", "PGBOAlgorithm"
  )
  if (length(optimizer) > 0L && nzchar(optimizer) &&
      !optimizer %in% validOptimizers)
    stop(sprintf(
      "Unknown optimizer '%s'. Must be one of: %s.",
      optimizer, paste(validOptimizers, collapse = ", ")
    ))

  .Optimization_S7(
    optimisationDesign           = optimisationDesign,
    optimisationAlgorithmOutputs = optimisationAlgorithmOutputs,
    name                         = name,
    modelParameters              = modelParameters,
    modelEquations               = modelEquations,
    modelFromLibrary             = modelFromLibrary,
    modelError                   = modelError,
    designs                      = designs,
    outputs                      = outputs,
    fimType                      = fimType,
    odeSolverParameters          = odeSolverParameters,
    optimizer                    = optimizer,
    optimizerParameters          = optimizerParameters
  )
}

# ==============================================================================
# the new_generic
# ==============================================================================

# ==============================================================================
#' @title Define Optimization Algorithm
#' @name defineOptimizationAlgorithm
#' @description
#' This method initializes the selected optimization algorithm using the specific
#' hyperparameters (such as lambda, delta, iterations) extracted from the project options.
#' It prepares the algorithmic object for subsequent use by the \code{optimizeDesign} function.
#' @param optimization An object of class \code{Optimization} containing
#' the optimization settings and design parameters.
#' @param ... Additional arguments.
#' @return An object of class \code{OptimizationAlgorithm}
#' @template copyright
#' @export
# ==============================================================================

defineOptimizationAlgorithm = new_generic("defineOptimizationAlgorithm", c("optimization"))

# ==============================================================================
#' @title Generate Fisher Information Matrices (FIM) from Design Constraints
#' @name generateFimsFromConstraints
#' @description
#' This method explores the design space defined by the project constraints and
#' computes the Fisher Information Matrix (FIM) for every candidate elementary
#' design arm. These matrices are then stored as a library to be used by the
#' optimization algorithms.
#' @param optimization An object of class \code{Optimization}
#' containing the model definitions, parameter values, and design constraints.
#' @param ... Additional arguments.
#' @return The updated \code{optimization} object, where the slot
#' \code{fisherMatrices} contains the list of matrices calculated for each
#' candidate arm.
#' @template copyright
#' @export
# ==============================================================================

generateFimsFromConstraints = new_generic("generateFimsFromConstraints", c("optimization"))

# ==============================================================================
#' @title Visualize the distribution of optimal design weights
#' @name plotWeights
#' @description
#' Generates a bar plot showing the weights assigned to each candidate arm
#' after the optimization process. This represents the proportion of the
#' total population that should be allocated to each specific design.
#' @param optimization An object of class \code{Optimization} that has been optimized.
#' @param ... Additional arguments.
#' @return A \code{ggplot2} bar plot of the optimized weights.
#' @examples
#' \dontrun{
#' # plot the weights from the optimizationMultiplicativePopulationFIMObject
#' weights = plotWeights( optimizationMultiplicativePopulationFIMObject )
#' print(weights)
#' }
#' @template copyright
#' @export
# ==============================================================================

plotWeights = new_generic("plotWeights", c("optimization"))

# ==============================================================================
#' @title plotFrequencies: visualize optimal frequencies for the Fedorov-Wynn algorithm
#' @name plotFrequencies
#' @description
#' Generates a bar plot showing the frequencies (normalized counts) of the
#' design arms selected by the Fedorov-Wynn algorithm. This plot identifies
#' the support points of the optimal discrete design.
#' @param optimization An object of class \code{Optimization} containing
#' Fedorov-Wynn algorithm results.
#' @param ... Additional arguments.
#' @return A \code{ggplot2} bar plot of the optimal frequencies.
#' @examples
#' \dontrun{
#' # plot frequencie from optimizationFedorovWynnPopulationFIMObject
#' frequencies = plotFrequencies( optimizationFedorovWynnPopulationFIMObject )
#' print(frequencies)
#' }
#' @template copyright
#' @export
# ==============================================================================

plotFrequencies = new_generic("plotFrequencies", c("optimization"))

# ==============================================================================
#' @title Optimize Study Design
#' @name optimizeDesign
#' @description
#' Dispatches the optimization of a study design to the appropriate algorithm.
#' Methods are available for all PFIM optimization algorithms:
#' \code{\link{MultiplicativeAlgorithm}}, \code{\link{FedorovWynnAlgorithm}},
#' \code{\link{SimplexAlgorithm}}, \code{\link{PSOAlgorithm}},
#' and \code{\link{PGBOAlgorithm}}.
#' @param optimizationObject An object of class \code{\link{Optimization}}
#' containing the design space, model, and objective function settings.
#' @param optimizationAlgorithm An object of the algorithm class to use
#' (\code{MultiplicativeAlgorithm}, \code{FedorovWynnAlgorithm}, etc.).
#' @param \dots Additional arguments passed to methods
#' @return The updated \code{optimizationObject} with optimized designs,
#' final FIM value, and algorithm-specific outputs stored in the relevant slots.
#' @template copyright
#' @export
# ==============================================================================

optimizeDesign = new_generic("optimizeDesign", c("optimizationObject", "optimizationAlgorithm"))

# ==============================================================================
#' @title Generate Algorithm Constraints Table for Reporting
#' @name constraintsTableForReport
#' @description
#' Extracts and formats the design constraints and algorithm hyperparameters
#' into a structured table suitable for inclusion in PFIM reports.
#' Methods are available for all optimization algorithms:
#' \code{\link{MultiplicativeAlgorithm}}, \code{\link{FedorovWynnAlgorithm}},
#' \code{\link{SimplexAlgorithm}}, \code{\link{PSOAlgorithm}},
#' and \code{\link{PGBOAlgorithm}}.
#' @param optimizationAlgorithm An object of one of the PFIM optimization
#' algorithm classes.
#' @param \dots Additional arguments passed to methods.
#' @return A \code{kable} object containing the formatted constraints table,
#' listing arm-level and algorithm-level settings.
#' @template copyright
#' @export
# ==============================================================================

constraintsTableForReport = new_generic("constraintsTableForReport", c("optimizationAlgorithm"))

# ==============================================================================
# the methods
# ==============================================================================

method(generateFimsFromConstraints, .Optimization_S7) = function(optimization) {

  listArms = list()
  listFimsAlgoFW = list()
  listFimsAlgoMult = list()

  samplingsForFedorovWynnAlgo = list()

  # set the evaluation parameters from the optimization object
  evaluation = Evaluation(name = "internalFimEvaluation",
                          modelEquations = prop(optimization, "modelEquations"),
                          modelParameters = prop(optimization, "modelParameters"),
                          modelError = prop(optimization, "modelError"),
                          designs =  prop(optimization, "designs"),
                          fimType = prop(optimization, "fimType"),
                          outputs = prop(optimization, "outputs"),
                          odeSolverParameters = prop(optimization, "odeSolverParameters"))

  # Extract the designs from the optimization object
  designs = prop(optimization, "designs")
  designNames = map(designs, ~ prop(.x, "name"))

  # All combinations for administration times constraints
  dosesForFIMs = map(designs, ~ generateDosesCombination(.x)) %>% set_names(designNames)

  # All combinations for sampling times constraints
  samplingsForFIMs = map(designs, ~ generateSamplingTimesCombination(.x)) %>% set_names(designNames)

  # evaluate the FIMs
  # for each dose combination associate each sampling time combination
  for (design in designs)
  {
    numberOfFims = 1

    designName = prop(design, "name")
    arms = prop(design, "arms")

    dosesForFIMs = dosesForFIMs[[designName]]
    numberOfDoses = dosesForFIMs$numberOfDoses

    for (iterDose in seq(numberOfDoses))
    {
      # assign the new doses for each arm
      arms = map(arms, function(arm)
      {
        armName = prop(arm, "name")
        administrations = prop(arm, "administrations")
        administrations = map(administrations, function(administration)
        {
          outcome = prop(administration, "outcome")
          prop(administration, "dose") = dosesForFIMs[[armName]][[outcome]][iterDose]
          return(administration)
        })
        prop(arm, "administrations") = administrations
        return(arm)
      })

      # Create combination indices for the sampling times
      combinationIndicesSamplingTimes = expand.grid(map(samplingsForFIMs[[designName]], ~ seq_along(.x)))
      numberOfCombinationIndicesSamplingTimes = nrow(combinationIndicesSamplingTimes)

      for (iterCombinationIndicesSamplingTimes in 1:numberOfCombinationIndicesSamplingTimes)
      {
        # Update arms with new sampling times for the current combination
        armsWithNewSamplingTimes = map(arms, function(arm) {
          armName = prop(arm, 'name')
          indexSamplingsForFims = combinationIndicesSamplingTimes[iterCombinationIndicesSamplingTimes, armName]

          samplingsForFedorovWynnAlgoTmp = pluck(samplingsForFIMs, designName, armName, indexSamplingsForFims) %>%
            map(~ prop(.x, "samplings")) %>%
            list_c()  # replaces deprecated flatten_dbl() (purrr >= 1.0)

          prop(arm, "samplingTimes") = pluck(samplingsForFIMs, designName, armName, indexSamplingsForFims)
          list(arm = arm,  samplingsForFedorovWynnAlgoTmp = samplingsForFedorovWynnAlgoTmp)
        })

        armsWithNewSamplingTimes = pluck(armsWithNewSamplingTimes, 1)

        # samplings for FW method
        samplingsForFedorovWynnAlgo[[designName]][[numberOfFims]] = armsWithNewSamplingTimes$samplingsForFedorovWynnAlgoTmp

        # Update the design with the new arms
        prop(design, "arms") = list(armsWithNewSamplingTimes$arm)
        prop(evaluation, "designs") = list(design)

        # design evaluation and get the FIM
        evaluationFIM = run(evaluation)
        fim = getFisherMatrix(evaluationFIM)
        fisherMatrix = fim$fisherMatrix

        # reshape the fims
        dimFim = nrow(fisherMatrix)
        dimVectorTriangularInfWithDiagFisherMatrices = dimFim*(dimFim+1)/2
        fisherMatrixForAlgoFW = fisherMatrix[ rev(lower.tri(t(fisherMatrix), diag = TRUE)) ]
        fisherMatrixForAlgoFW = matrix(fisherMatrixForAlgoFW , ncol = dimVectorTriangularInfWithDiagFisherMatrices, byrow = TRUE)

        listArms[[designName]][[numberOfFims]] = armsWithNewSamplingTimes
        listFimsAlgoFW[[designName]][[numberOfFims]] = fisherMatrixForAlgoFW
        listFimsAlgoMult[[designName]][[numberOfFims]] = fisherMatrix
        # Print the iteration for progress tracking
        message(paste0("Evaluation of the FIMs: ",  numberOfFims, "/", numberOfCombinationIndicesSamplingTimes*numberOfDoses))
        numberOfFims = numberOfFims + 1
      } # end samplingTimes
    } #end doses
  } # end designs
  return(list(listArms = listArms, dimFim = dimFim, listFimsAlgoFW = listFimsAlgoFW ,
              listFimsAlgoMult = listFimsAlgoMult, samplingsForFedorovWynnAlgo = samplingsForFedorovWynnAlgo)) }

# ==============================================================================

method(defineOptimizationAlgorithm, .Optimization_S7) = function(optimization)
{
  # Read the optimizer name stored in the dedicated slot.
  # Since Optimization() always returns a plain Optimization object (not a
  # subclass), we read the "optimizer" slot, not class()[1].
  optimizerName = prop(optimization, "optimizer")

  if (length(optimizerName) == 0L || !nzchar(optimizerName))
    stop("@optimizer is empty. Use Optimization(optimizer = 'AlgorithmName', ...).")

  # Create an empty dispatch token whose S7 class selects the right
  # optimizeDesign() method.  All data is in prop(optimization, ...) — not here.
  optimizationAlgorithm = switch(
    optimizerName,
    "MultiplicativeAlgorithm" = MultiplicativeAlgorithm(),
    "FedorovWynnAlgorithm"    = FedorovWynnAlgorithm(),
    "PSOAlgorithm"            = PSOAlgorithm(),
    "PGBOAlgorithm"           = PGBOAlgorithm(),
    "SimplexAlgorithm"        = SimplexAlgorithm(),
    stop(sprintf("Unknown optimizer: '%s'.", optimizerName))
  )

  return(optimizationAlgorithm)
}

# ==============================================================================

method(run, .Optimization_S7) = function(pfimproject)
{
  # set the optimization parameters
  optimizationAlgorithm = defineOptimizationAlgorithm(pfimproject)

  # define the type of the Fim
  prop(pfimproject, "fim") = defineFim(pfimproject)

  # define model equations
  modelFromLibraryOfModel = prop(pfimproject, "modelFromLibrary")
  if (length(modelFromLibraryOfModel) != 0) { prop(pfimproject, "modelEquations") = defineModelEquationsFromLibraryOfModel(pfimproject) }

  # Run the optimization process
  optimizationDesign = optimizeDesign(pfimproject, optimizationAlgorithm )

  return(optimizationDesign)
}

# ==============================================================================

method(show, .Optimization_S7) = function(pfimproject)
{
  optimisationDesign = prop(pfimproject, "optimisationDesign")
  evaluationOptimalDesign = optimisationDesign$evaluationOptimalDesign
  evaluationInitialDesign = optimisationDesign$evaluationInitialDesign

  # initial design
  designs = prop(evaluationInitialDesign, "designs")
  arms = map(designs, ~ prop(.x, "arms"))
  armsData = list_flatten(map(pluck(arms,1), getArmData))
  initialDesignData = map_dfr(armsData, ~ as.data.frame(.x, stringsAsFactors = FALSE))
  colnames(initialDesignData) = c("Arms name" , "Number of subjects", "Outcome", "Dose","Sampling times")

  # optimal design
  designs = prop(evaluationOptimalDesign, "designs")
  arms = map(designs, ~ prop(.x, "arms"))
  armsData = list_flatten(map(pluck(arms,1), getArmData))
  optimalDesignData = map_dfr(armsData, ~ as.data.frame(.x, stringsAsFactors = FALSE))
  colnames(optimalDesignData) = c("Arms name" , "Number of subjects", "Outcome", "Dose","Sampling times")

  # Fisher matrix and SE
  fim = prop(evaluationInitialDesign, "fim")
  fimInitialDesign = setEvaluationFim(fim, evaluationInitialDesign)
  fim = prop(evaluationOptimalDesign, "fim")
  fimOptimalDesign = setEvaluationFim(fim, evaluationOptimalDesign)

  cat("\n===================================== \n")
  cat("  Initial design \n")
  cat("===================================== \n\n")
  print(initialDesignData)
  showFIM(fimInitialDesign)
  cat("\n===================================== \n")
  cat("  Optimal design \n")
  cat("===================================== \n\n")
  print(optimalDesignData)
  showFIM(fimOptimalDesign)
}

# ==============================================================================

method(getFisherMatrix, .Optimization_S7) = function(pfimproject)
{
  optimisationDesign = prop(pfimproject, "optimisationDesign")
  evaluationOptimalDesign = optimisationDesign$evaluationOptimalDesign
  fim = prop(evaluationOptimalDesign, "fim")
  fim = setEvaluationFim(fim, evaluationOptimalDesign)
  fisherMatrix = prop(fim, "fisherMatrix")
  fixedEffects = prop(fim, "fixedEffects")
  varianceEffects = prop(fim, "varianceEffects")
  return(list(fisherMatrix = fisherMatrix, fixedEffects = fixedEffects, varianceEffects = varianceEffects))
}

# ==============================================================================

method(getSE, .Optimization_S7) = function(pfimproject)
{
  optimisationDesign = prop(pfimproject, "optimisationDesign")
  evaluationOptimalDesign = optimisationDesign$evaluationOptimalDesign
  fim = prop(evaluationOptimalDesign, "fim")
  fim = setEvaluationFim(fim, evaluationOptimalDesign)
  SEAndRSE = prop(fim, "SEAndRSE")
  SE = SEAndRSE$SE
  return(SE)
}

# ==============================================================================

method(getRSE, .Optimization_S7) = function(pfimproject)
{
  optimisationDesign = prop(pfimproject, "optimisationDesign")
  evaluationOptimalDesign = optimisationDesign$evaluationOptimalDesign
  fim = prop(evaluationOptimalDesign, "fim")
  fim = setEvaluationFim(fim, evaluationOptimalDesign)
  SEAndRSE = prop(fim, "SEAndRSE")
  RSE = SEAndRSE$RSE
  return(RSE)
}

# ==============================================================================

method(getShrinkage, .Optimization_S7) = function(pfimproject)
{
  optimisationDesign = prop(pfimproject, "optimisationDesign")
  evaluationOptimalDesign = optimisationDesign$evaluationOptimalDesign
  fim = prop(evaluationOptimalDesign, "fim")
  fim = setEvaluationFim(fim, evaluationOptimalDesign)
  shrinkage = prop(fim, "shrinkage")
  return(shrinkage)
}

# ==============================================================================

method(getDeterminant, .Optimization_S7) = function(pfimproject)
{
  optimisationDesign = prop(pfimproject, "optimisationDesign")
  evaluationOptimalDesign = optimisationDesign$evaluationOptimalDesign
  fisherMatrix = getFisherMatrix(evaluationOptimalDesign)
  return(det(fisherMatrix$fisherMatrix))
}

# ==============================================================================

method(getCorrelationMatrix, .Optimization_S7) = function(pfimproject)
{
  # The asymptotic correlation matrix of the estimators is cov2cor(FIM^{-1}),
  # NOT cor(FIM). cor() would treat the FIM columns as data vectors — wrong.
  # Correct: Var(theta_hat) ~ FIM^{-1}  =>  R = cov2cor(FIM^{-1}).
  optimisationDesign      = prop(pfimproject, "optimisationDesign")
  evaluationOptimalDesign = optimisationDesign$evaluationOptimalDesign
  fisherMatrix            = getFisherMatrix(evaluationOptimalDesign)$fisherMatrix
  return(cov2cor(solve(fisherMatrix)))
}

# ==============================================================================

method(getDcriterion, .Optimization_S7) = function(pfimproject)
{
  optimisationDesign = prop(pfimproject, "optimisationDesign")
  evaluationOptimalDesign = optimisationDesign$evaluationOptimalDesign
  fim = prop(evaluationOptimalDesign, "fim")
  fim = setEvaluationFim(fim, evaluationOptimalDesign)
  return(Dcriterion(fim))
}

# ==============================================================================

method(plotSensitivityIndices, .Optimization_S7) = function(pfimproject)
{
  optimisationDesign = prop(pfimproject, "optimisationDesign")
  evaluationOptimalDesign = optimisationDesign$evaluationOptimalDesign
  plotSensitivityIndicesOptimalDesign = plotSensitivityIndices(evaluationOptimalDesign)
  return(plotSensitivityIndicesOptimalDesign)
}

# ==============================================================================

method(plotSE, .Optimization_S7) = function(pfimproject)
{
  optimisationDesign      = prop(pfimproject, "optimisationDesign")
  evaluationOptimalDesign = optimisationDesign$evaluationOptimalDesign
  fim                     = prop(evaluationOptimalDesign, "fim")
  fim                     = setEvaluationFim(fim, evaluationOptimalDesign)
  plotSEResult            = plotSEFIM(fim, evaluationOptimalDesign)
  return(plotSEResult)
}

# ==============================================================================

method(plotRSE, .Optimization_S7) = function(pfimproject)
{
  optimisationDesign      = prop(pfimproject, "optimisationDesign")
  evaluationOptimalDesign = optimisationDesign$evaluationOptimalDesign
  fim                     = prop(evaluationOptimalDesign, "fim")
  fim                     = setEvaluationFim(fim, evaluationOptimalDesign)
  plotRSEResult           = plotRSEFIM(fim, evaluationOptimalDesign)
  return(plotRSEResult)
}

# ==============================================================================

method(plotWeights, .Optimization_S7) = function(optimization, thresholdWeights = 0)
{
  optimisationAlgorithmOutputs = prop(optimization, "optimisationAlgorithmOutputs")
  optimizationAlgorithm        = optimisationAlgorithmOutputs$optimizationAlgorithm
  plotWeightsMultiplicativeAlgorithm(optimization, optimizationAlgorithm, thresholdWeights)
}

# ==============================================================================

method(plotFrequencies, .Optimization_S7) = function(optimization, thresholdFrequencies = 0)
{
  optimisationAlgorithmOutputs = prop(optimization, "optimisationAlgorithmOutputs")
  optimizationAlgorithm        = optimisationAlgorithmOutputs$optimizationAlgorithm
  plotFrequenciesFedorovWynnAlgorithm(optimization, optimizationAlgorithm, thresholdFrequencies)
}

# ==============================================================================

method(Report, .Optimization_S7) = function(pfimproject, outputPath, outputFile, plotOptions )
{
  # projectName
  projectName = prop(pfimproject, "name")

  # slots optimization
  optimisationDesign = prop(pfimproject, "optimisationDesign")
  evaluationOptimalDesign = optimisationDesign$evaluationOptimalDesign
  evaluationInitialDesign = optimisationDesign$evaluationInitialDesign

  # outputs
  evaluationOutputs = prop(pfimproject , "outputs")

  # model
  model = defineModelType(evaluationInitialDesign )
  modelEquations = prop(model, "modelEquations")

  # model error table
  modelError = prop(evaluationInitialDesign, "modelError")
  modelError = map(modelError, getModelErrorData)
  modelErrorData = map_dfr(modelError, ~ as.data.frame(.x, stringsAsFactors = FALSE))
  colnames(modelErrorData) = c("Output", "Type", "$\\sigma_{slope}$", "$\\sigma_{inter}$")

  modelErrorTable = kbl(modelErrorData, align = c("c","c","c","c")) %>%
    kable_styling(bootstrap_options = c( "hover"), full_width = FALSE, position = "center", font_size = 13)

  # model parameters table
  modelParameters = prop(evaluationInitialDesign, "modelParameters")
  modelParameters = map(modelParameters, getModelParametersData)
  modelParametersData = map_dfr(modelParameters, ~ as.data.frame(.x, stringsAsFactors = FALSE))
  colnames(modelParametersData) = c("Parameter","$\\mu$","$\\omega$","Distribution", paste0("$\\mu$"," fixed"), paste0("$\\omega$"," fixed"))

  modelParametersTable = kbl(modelParametersData, align = c("l","l","l","c","c","c")) %>%
    kable_styling(bootstrap_options = c( "hover"), full_width = FALSE, position = "center", font_size = 13)

  # arms
  designs = prop(evaluationInitialDesign, "designs")
  arms = map(designs, ~ prop(.x, "arms"))
  armsData = list_flatten(map(pluck(arms,1), getArmData))

  # administration table
  administration = list_flatten(map(pluck(arms, 1), armAdministration))
  administrationData = map_dfr(administration, ~ as.data.frame(.x, stringsAsFactors = FALSE))
  colnames(administrationData) = c("Design name","Arms name" , "Number of subject ", "Outcome", "Dose","Time dose", "$\\tau$", "$T_{inf}$")

  administrationTable = kbl(administrationData, align = c("l","l","l","c","c","c","c")) %>%
    kable_styling(bootstrap_options = c( "hover"), full_width = FALSE, position = "center", font_size = 13)

  # initial design
  initialDesignData = map_dfr(armsData, ~ as.data.frame(.x, stringsAsFactors = FALSE))
  colnames(initialDesignData) = c("Arms name" , "Number of subjects", "Outcome", "Dose","Sampling times")

  initialDesignTable = kbl(initialDesignData, align = c("l","c","c","c")) %>%
    kable_styling(bootstrap_options = c( "hover"), full_width = FALSE, position = "center", font_size = 13)

  # Fisher matrix and SE
  fim = prop(evaluationInitialDesign, "fim")
  fim = setEvaluationFim(fim, evaluationInitialDesign)
  fimInitialDesignTable = tablesForReport(fim, evaluationInitialDesign)

  # design constraints
  optimisationAlgorithmOutputs = prop(pfimproject, "optimisationAlgorithmOutputs")
  optimizationAlgorithm = optimisationAlgorithmOutputs$optimizationAlgorithm
  constraintsTable = constraintsTableForReport(optimizationAlgorithm, arms)

  # optimal design table
  designs = prop(evaluationOptimalDesign, "designs")
  arms = map(designs, ~ prop(.x, "arms"))
  armsData = list_flatten(map(pluck(arms,1), getArmData))
  optimalDesignData = map_dfr(armsData, ~ as.data.frame(.x, stringsAsFactors = FALSE))
  colnames(optimalDesignData) = c("Arms name" , "Number of subjects", "Outcome", "Dose","Sampling times")

  optimalDesignTable = kbl(optimalDesignData, align = c("l","c","c","c","c","c")) %>%
    kable_styling(bootstrap_options = c( "hover"), full_width = FALSE, position = "center", font_size = 13)

  # Fisher matrix and SE
  fim = prop(evaluationOptimalDesign, "fim")
  fim = setEvaluationFim(fim, evaluationOptimalDesign)
  fimOptimalTable = tablesForReport(fim, evaluationOptimalDesign)

  # plotsEvaluation & plotSensitivityIndices
  plotsEvaluation = plotEvaluation(evaluationOptimalDesign, plotOptions)
  sensitivityPlot = plotSensitivityIndices(evaluationOptimalDesign, plotOptions)
  sePlot          = plotSE(evaluationOptimalDesign)
  rsePlot         = plotRSE(evaluationOptimalDesign)

  reportData = list(
    evaluationOutputs        = evaluationOutputs,
    modelEquations           = modelEquations,
    modelErrorTable          = modelErrorTable,
    modelParametersTable     = modelParametersTable,
    administrationTable      = administrationTable,
    initialDesignTable       = initialDesignTable,
    constraintsTableForReport = constraintsTable,
    fimInitialDesignTable    = fimInitialDesignTable,
    optimalDesignTable       = optimalDesignTable,
    fimOptimalTable          = fimOptimalTable,
    plotsEvaluation          = plotsEvaluation,
    plotSensitivityIndices   = sensitivityPlot,
    plotSE                   = sePlot,
    plotRSE                  = rsePlot,
    fim                      = fim,
    pfimproject               = pfimproject,
    projectName              = projectName
  )

  generateReportOptimization(fim, optimizationAlgorithm, reportData, outputPath = outputPath, outputFile = outputFile)

}
